FROM ubuntu:latest 
RUN apt-get update && apt-get install -y\
    build-essential \
    python3\
    python3-pip\
    make\
    && rm -rf var/lib/apt/lists/*
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt
COPY . /app/

WORKDIR /app/

RUN make 
RUN ./expriement_1.sh
